import applications_operator_theory_probability_theory_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace applications_operator_theory_probability_theory_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end applications_operator_theory_probability_theory_theorem_canonical_lane_mathlib
end HautevilleHouse
